// <auto-generated />
using System;
using LeanProductionAnalytics.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeanProductionAnalytics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("LeanProductionAnalytics.Domain.JigExchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId")
                        .IsUnique();

                    b.ToTable("JigExchange");
                });

            modelBuilder.Entity("LeanProductionAnalytics.Domain.JigStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JigExchangeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JigExchangeId");

                    b.ToTable("JigStep");
                });

            modelBuilder.Entity("LeanProductionAnalytics.Domain.Production", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("JigExchangeRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QueueTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RejectQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SetupTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shift")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("LeanProductionAnalytics.Domain.JigExchange", b =>
                {
                    b.HasOne("LeanProductionAnalytics.Domain.Production", "Production")
                        .WithOne("JigExchange")
                        .HasForeignKey("LeanProductionAnalytics.Domain.JigExchange", "ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("LeanProductionAnalytics.Domain.JigStep", b =>
                {
                    b.HasOne("LeanProductionAnalytics.Domain.JigExchange", "JigExchange")
                        .WithMany("JigSteps")
                        .HasForeignKey("JigExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JigExchange");
                });

            modelBuilder.Entity("LeanProductionAnalytics.Domain.JigExchange", b =>
                {
                    b.Navigation("JigSteps");
                });

            modelBuilder.Entity("LeanProductionAnalytics.Domain.Production", b =>
                {
                    b.Navigation("JigExchange");
                });
#pragma warning restore 612, 618
        }
    }
}
